// The Android Gradle Plugin builds the native code with the Android NDK.

group = "com.nkming.nc_photos.np_exiv2"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // The Android Gradle Plugin knows how to build native code with the NDK.
        classpath 'com.android.tools.build:gradle:8.13.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"

android {
    namespace = "com.nkming.nc_photos.np_exiv2"
   	compileSdk 35
    ndkVersion "29.0.14206865"

    // Invoke the shared CMake build with the Android Gradle Plugin.
    externalNativeBuild {
        cmake {
            path = "../src/CMakeLists.txt"
            version '3.31.6'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk 24
    }

    buildTypes {
        all {
            ndk.abiFilters.clear()
            ndk.abiFilters.addAll(["arm64-v8a"])
        }
    }
}
