name: np_login_flow
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.11.0"
  flutter: ">=3.41.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  http: ^1.1.2
  logging: ^1.2.0
  np_api:
    path: ../np_api
  np_common:
    path: ../np_common
  np_log:
    path: ../np_log
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-3.0.0
      path: to_string
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.13.1
  dart_style: 3.1.2
  flutter_test:
    sdk: flutter
  np_lints:
    path: ../np_lints
  np_log_build:
    path: ../np_log_build
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-3.0.1
      path: to_string_build
