name: np_collection
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  np_math:
    path: ../np_math
  quiver: ^3.2.1

dev_dependencies:
  np_lints:
    path: ../np_lints
  test: ^1.22.1
