name: np_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.0"

dependencies:
  flutter_lints: ^4.0.0

dev_dependencies:
  dart_style: 3.1.2
