name: np_codegen_build
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  np_codegen:
    path: ../codegen
  source_gen: ^1.5.0

dev_dependencies:
  build_test: ^2.1.5
  np_lints:
    path: ../np_lints
  path: ^1.8.3
  rxdart: any
  test: ^1.22.1
