// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/np_ffi_torch.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class NpFfiTorchBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NpFfiTorchBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NpFfiTorchBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void torchRgb8ImageFree(ffi.Pointer<TorchRgb8Image> that) {
    return _torchRgb8ImageFree(that);
  }

  late final _torchRgb8ImageFreePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TorchRgb8Image>)>
      >('torchRgb8ImageFree');
  late final _torchRgb8ImageFree = _torchRgb8ImageFreePtr
      .asFunction<void Function(ffi.Pointer<TorchRgb8Image>)>();

  void torchRgba8ImageFree(ffi.Pointer<TorchRgba8Image> that) {
    return _torchRgba8ImageFree(that);
  }

  late final _torchRgba8ImageFreePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TorchRgba8Image>)>
      >('torchRgba8ImageFree');
  late final _torchRgba8ImageFree = _torchRgba8ImageFreePtr
      .asFunction<void Function(ffi.Pointer<TorchRgba8Image>)>();

  ffi.Pointer<TorchRgb8Image> inferRealEsrgan(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferRealEsrgan(input, modelPath);
  }

  late final _inferRealEsrganPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferRealEsrgan');
  late final _inferRealEsrgan = _inferRealEsrganPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgb8Image> inferNafnet(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferNafnet(input, modelPath);
  }

  late final _inferNafnetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferNafnet');
  late final _inferNafnet = _inferNafnetPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgb8Image> inferEfficientDerain(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferEfficientDerain(input, modelPath);
  }

  late final _inferEfficientDerainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferEfficientDerain');
  late final _inferEfficientDerain = _inferEfficientDerainPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgb8Image> inferNeurop(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferNeurop(input, modelPath);
  }

  late final _inferNeuropPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferNeurop');
  late final _inferNeurop = _inferNeuropPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgb8Image> inferZeroDce(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferZeroDce(input, modelPath);
  }

  late final _inferZeroDcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferZeroDce');
  late final _inferZeroDce = _inferZeroDcePtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgba8Image> inferEfficientSamExtract(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<TorchPoint> points,
    ffi.Pointer<ffi.Int> pointLabels,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferEfficientSamExtract(input, points, pointLabels, modelPath);
  }

  late final _inferEfficientSamExtractPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgba8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<TorchPoint>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferEfficientSamExtract');
  late final _inferEfficientSamExtract = _inferEfficientSamExtractPtr
      .asFunction<
        ffi.Pointer<TorchRgba8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<TorchPoint>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
        )
      >();
}

final class TorchRgb8Image extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> pixel;

  @ffi.UnsignedInt()
  external int width;

  @ffi.UnsignedInt()
  external int height;
}

final class TorchRgba8Image extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> pixel;

  @ffi.UnsignedInt()
  external int width;

  @ffi.UnsignedInt()
  external int height;
}

final class TorchPoint extends ffi.Struct {
  @ffi.Int()
  external int x;

  @ffi.Int()
  external int y;
}
