// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/np_ffi_torch.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class NpFfiTorchBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NpFfiTorchBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NpFfiTorchBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void torchRgb8ImageFree(ffi.Pointer<TorchRgb8Image> that) {
    return _torchRgb8ImageFree(that);
  }

  late final _torchRgb8ImageFreePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TorchRgb8Image>)>
      >('torchRgb8ImageFree');
  late final _torchRgb8ImageFree = _torchRgb8ImageFreePtr
      .asFunction<void Function(ffi.Pointer<TorchRgb8Image>)>();

  ffi.Pointer<TorchRgb8Image> inferRealEsrgan(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferRealEsrgan(input, modelPath);
  }

  late final _inferRealEsrganPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferRealEsrgan');
  late final _inferRealEsrgan = _inferRealEsrganPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgb8Image> inferNafnet(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferNafnet(input, modelPath);
  }

  late final _inferNafnetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferNafnet');
  late final _inferNafnet = _inferNafnetPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<TorchRgb8Image> inferEfficientDerain(
    ffi.Pointer<TorchRgb8Image> input,
    ffi.Pointer<ffi.Char> modelPath,
  ) {
    return _inferEfficientDerain(input, modelPath);
  }

  late final _inferEfficientDerainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TorchRgb8Image> Function(
            ffi.Pointer<TorchRgb8Image>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inferEfficientDerain');
  late final _inferEfficientDerain = _inferEfficientDerainPtr
      .asFunction<
        ffi.Pointer<TorchRgb8Image> Function(
          ffi.Pointer<TorchRgb8Image>,
          ffi.Pointer<ffi.Char>,
        )
      >();
}

final class TorchRgb8Image extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> pixel;

  @ffi.UnsignedInt()
  external int width;

  @ffi.UnsignedInt()
  external int height;
}
