// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/np_ffi_torch.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class NpFfiTorchBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NpFfiTorchBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NpFfiTorchBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int getCoresCount() {
    return _getCoresCount();
  }

  late final _getCoresCountPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('getCoresCount');
  late final _getCoresCount = _getCoresCountPtr.asFunction<int Function()>();
}
