name: np_exiv2
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.11.0"
  flutter: ">=3.41.0"

dependencies:
  euc: ^1.0.6+8
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  logging: ^1.2.0
  np_common:
    path: ../np_common
  path: ^1.8.3
  plugin_platform_interface: ^2.0.2
  quiver: ^3.2.1
  time_machine2: ^0.14.0

dev_dependencies:
  dart_style: 3.1.2
  ffigen: ^19.0.0
  flutter_test:
    sdk: flutter
  np_lints:
    path: ../np_lints

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # Please refer to README.md for a detailed explanation.
  plugin:
    platforms:
      android:
        ffiPlugin: true
