name: np_exiv2
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  euc: ^1.0.6+8
  ffi: ^2.1.3
  logging: ^1.2.0
  np_common:
    path: ../np_common
  path: ^1.8.3
  quiver: ^3.2.1

dev_dependencies:
  ffigen: ^14.0.1
  np_lints:
    path: ../np_lints
