// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct QueryResult: Hashable {
  var id: String
  var displayName: String? = nil
  var dateModified: Int64? = nil
  var mimeType: String? = nil
  var dateTaken: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var size: Int64? = nil
  var androidUri: String? = nil
  var androidPath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueryResult? {
    let id = pigeonVar_list[0] as! String
    let displayName: String? = nilOrValue(pigeonVar_list[1])
    let dateModified: Int64? = nilOrValue(pigeonVar_list[2])
    let mimeType: String? = nilOrValue(pigeonVar_list[3])
    let dateTaken: Int64? = nilOrValue(pigeonVar_list[4])
    let width: Int64? = nilOrValue(pigeonVar_list[5])
    let height: Int64? = nilOrValue(pigeonVar_list[6])
    let size: Int64? = nilOrValue(pigeonVar_list[7])
    let androidUri: String? = nilOrValue(pigeonVar_list[8])
    let androidPath: String? = nilOrValue(pigeonVar_list[9])

    return QueryResult(
      id: id,
      displayName: displayName,
      dateModified: dateModified,
      mimeType: mimeType,
      dateTaken: dateTaken,
      width: width,
      height: height,
      size: size,
      androidUri: androidUri,
      androidPath: androidPath
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      displayName,
      dateModified,
      mimeType,
      dateTaken,
      width,
      height,
      size,
      androidUri,
      androidPath,
    ]
  }
  static func == (lhs: QueryResult, rhs: QueryResult) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return QueryResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? QueryResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MyHostApi {
  func getFilesSummary(dirWhitelist: [String]?, completion: @escaping (Result<[String: Int64], Error>) -> Void)
  func queryFiles(fileIds: [String]?, platformIdentifiers: [String]?, timeRangeBeg: Int64?, isTimeRangeBegInclusive: Bool?, timeRangeEnd: Int64?, isTimeRangeEndInclusive: Bool?, dirWhitelist: [String]?, isAscending: Bool, offset: Int64?, limit: Int64?, completion: @escaping (Result<[QueryResult], Error>) -> Void)
  /// Read the content of a file identified by [platformIdentifier]
  ///
  /// [platformIdentifier] is platform-specific and should be a value returned
  /// in [QueryResult.platformIdentifier].
  func readFile(platformIdentifier: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Read the content of an image file, and downscale it to save memory
  ///
  /// Also see [readFile].
  func readThumbnail(platformIdentifier: String, width: Int64, height: Int64, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Copy a media file in internal storage to a public directory and return the
  /// platform identifier of the new file
  ///
  /// On Android, the file will be copied to Download/. On iOS, the file will be
  /// copied to the Photos library.
  func copyPrivateFileToPublicDir(srcFilePath: String, srcMime: String?, dstDir: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Copy a file identified by [platformIdentifier] to [dstPath]. No checking
  /// is done by this function so caller must ensure [privateDir] is a valid and
  /// accessible dir. Typically you can only write to one of the app private
  /// dirs.
  func copyFileToPrivateDir(platformIdentifier: String, dstPath: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Replace the content of a file identified by [platformIdentifier] with
  /// [bytes].
  ///
  /// On Android, [platformIdentifier] is a content URI managed by MediaStore.
  func replaceFile(platformIdentifier: String, bytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getFilesSummaryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.getFilesSummary\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFilesSummaryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dirWhitelistArg: [String]? = nilOrValue(args[0])
        api.getFilesSummary(dirWhitelist: dirWhitelistArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFilesSummaryChannel.setMessageHandler(nil)
    }
    let queryFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.queryFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryFilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileIdsArg: [String]? = nilOrValue(args[0])
        let platformIdentifiersArg: [String]? = nilOrValue(args[1])
        let timeRangeBegArg: Int64? = nilOrValue(args[2])
        let isTimeRangeBegInclusiveArg: Bool? = nilOrValue(args[3])
        let timeRangeEndArg: Int64? = nilOrValue(args[4])
        let isTimeRangeEndInclusiveArg: Bool? = nilOrValue(args[5])
        let dirWhitelistArg: [String]? = nilOrValue(args[6])
        let isAscendingArg = args[7] as! Bool
        let offsetArg: Int64? = nilOrValue(args[8])
        let limitArg: Int64? = nilOrValue(args[9])
        api.queryFiles(fileIds: fileIdsArg, platformIdentifiers: platformIdentifiersArg, timeRangeBeg: timeRangeBegArg, isTimeRangeBegInclusive: isTimeRangeBegInclusiveArg, timeRangeEnd: timeRangeEndArg, isTimeRangeEndInclusive: isTimeRangeEndInclusiveArg, dirWhitelist: dirWhitelistArg, isAscending: isAscendingArg, offset: offsetArg, limit: limitArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryFilesChannel.setMessageHandler(nil)
    }
    /// Read the content of a file identified by [platformIdentifier]
    ///
    /// [platformIdentifier] is platform-specific and should be a value returned
    /// in [QueryResult.platformIdentifier].
    let readFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.readFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let platformIdentifierArg = args[0] as! String
        api.readFile(platformIdentifier: platformIdentifierArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readFileChannel.setMessageHandler(nil)
    }
    /// Read the content of an image file, and downscale it to save memory
    ///
    /// Also see [readFile].
    let readThumbnailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.readThumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readThumbnailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let platformIdentifierArg = args[0] as! String
        let widthArg = args[1] as! Int64
        let heightArg = args[2] as! Int64
        api.readThumbnail(platformIdentifier: platformIdentifierArg, width: widthArg, height: heightArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readThumbnailChannel.setMessageHandler(nil)
    }
    /// Copy a media file in internal storage to a public directory and return the
    /// platform identifier of the new file
    ///
    /// On Android, the file will be copied to Download/. On iOS, the file will be
    /// copied to the Photos library.
    let copyPrivateFileToPublicDirChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.copyPrivateFileToPublicDir\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      copyPrivateFileToPublicDirChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let srcFilePathArg = args[0] as! String
        let srcMimeArg: String? = nilOrValue(args[1])
        let dstDirArg: String? = nilOrValue(args[2])
        api.copyPrivateFileToPublicDir(srcFilePath: srcFilePathArg, srcMime: srcMimeArg, dstDir: dstDirArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      copyPrivateFileToPublicDirChannel.setMessageHandler(nil)
    }
    /// Copy a file identified by [platformIdentifier] to [dstPath]. No checking
    /// is done by this function so caller must ensure [privateDir] is a valid and
    /// accessible dir. Typically you can only write to one of the app private
    /// dirs.
    let copyFileToPrivateDirChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.copyFileToPrivateDir\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      copyFileToPrivateDirChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let platformIdentifierArg = args[0] as! String
        let dstPathArg = args[1] as! String
        api.copyFileToPrivateDir(platformIdentifier: platformIdentifierArg, dstPath: dstPathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      copyFileToPrivateDirChannel.setMessageHandler(nil)
    }
    /// Replace the content of a file identified by [platformIdentifier] with
    /// [bytes].
    ///
    /// On Android, [platformIdentifier] is a content URI managed by MediaStore.
    let replaceFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.np_platform_local_media.MyHostApi.replaceFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      replaceFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let platformIdentifierArg = args[0] as! String
        let bytesArg = args[1] as! FlutterStandardTypedData
        api.replaceFile(platformIdentifier: platformIdentifierArg, bytes: bytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      replaceFileChannel.setMessageHandler(nil)
    }
  }
}
