name: np_image_format_interface
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.11.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  np_common:
    path: ../np_common
  np_platform_raw_image:
    path: ../np_platform_raw_image
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-3.0.0
      path: to_string

dev_dependencies:
  build_runner: ^2.13.1
  dart_style: 3.1.2
  np_lints:
    path: ../np_lints
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-3.0.1
      path: to_string_build
